// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiR9A9bckusWos7IVJn30b8ONA-u4JPQ',
    appId: '1:469399030001:web:840c027282b208ff1dc150',
    messagingSenderId: '469399030001',
    projectId: 'dyschool-1a25a',
    authDomain: 'dyschool-1a25a.firebaseapp.com',
    storageBucket: 'dyschool-1a25a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqR9c-bJDNDL1t8erwHtyvBi6jHbXC08',
    appId: '1:469399030001:android:73e5019f38dca3a81dc150',
    messagingSenderId: '469399030001',
    projectId: 'dyschool-1a25a',
    storageBucket: 'dyschool-1a25a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK6tUaBoz_7LOubVbkjAPCDx3O4Yzh-po',
    appId: '1:469399030001:ios:85717a80c77f14f41dc150',
    messagingSenderId: '469399030001',
    projectId: 'dyschool-1a25a',
    storageBucket: 'dyschool-1a25a.firebasestorage.app',
    iosBundleId: 'com.example.dyschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK6tUaBoz_7LOubVbkjAPCDx3O4Yzh-po',
    appId: '1:469399030001:ios:85717a80c77f14f41dc150',
    messagingSenderId: '469399030001',
    projectId: 'dyschool-1a25a',
    storageBucket: 'dyschool-1a25a.firebasestorage.app',
    iosBundleId: 'com.example.dyschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdiR9A9bckusWos7IVJn30b8ONA-u4JPQ',
    appId: '1:469399030001:web:ee33094256edc8ee1dc150',
    messagingSenderId: '469399030001',
    projectId: 'dyschool-1a25a',
    authDomain: 'dyschool-1a25a.firebaseapp.com',
    storageBucket: 'dyschool-1a25a.firebasestorage.app',
  );

}