// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLneQsBMq9jPfXBmTFZzeP-YeBpz50UGI',
    appId: '1:23606384393:web:0d547805e21fc64a80e5d8',
    messagingSenderId: '23606384393',
    projectId: 'dyschool-4ca88',
    authDomain: 'dyschool-4ca88.firebaseapp.com',
    storageBucket: 'dyschool-4ca88.appspot.com',
    measurementId: 'G-XTFC5B4656',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWFKfFkhhZPjz7fFyd5tfwiYAJ1I_5OQA',
    appId: '1:23606384393:android:109ffecb3c0e90ee80e5d8',
    messagingSenderId: '23606384393',
    projectId: 'dyschool-4ca88',
    storageBucket: 'dyschool-4ca88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7VrrqYFuWomESUqTBIfpMQu8FBZ9W19M',
    appId: '1:23606384393:ios:ba2ba415a67cb91f80e5d8',
    messagingSenderId: '23606384393',
    projectId: 'dyschool-4ca88',
    storageBucket: 'dyschool-4ca88.appspot.com',
    iosBundleId: 'com.example.dyschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7VrrqYFuWomESUqTBIfpMQu8FBZ9W19M',
    appId: '1:23606384393:ios:ba2ba415a67cb91f80e5d8',
    messagingSenderId: '23606384393',
    projectId: 'dyschool-4ca88',
    storageBucket: 'dyschool-4ca88.appspot.com',
    iosBundleId: 'com.example.dyschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLneQsBMq9jPfXBmTFZzeP-YeBpz50UGI',
    appId: '1:23606384393:web:b86abbdbfb9c0ded80e5d8',
    messagingSenderId: '23606384393',
    projectId: 'dyschool-4ca88',
    authDomain: 'dyschool-4ca88.firebaseapp.com',
    storageBucket: 'dyschool-4ca88.appspot.com',
    measurementId: 'G-RCC2732LWE',
  );

}